# Generated by Django 3.2 on 2022-02-27 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.CharField(blank=True, max_length=255)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ticket', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=5000)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('contributors', models.ManyToManyField(related_name='ticket_contributions', through='blog.BlogContributor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_review', models.CharField(max_length=128, null=True)),
                ('content', models.TextField(max_length=5000)),
                ('rating', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=11)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('contributors', models.ManyToManyField(related_name='review_contributions', through='blog.BlogContributor', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blogcontributor',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.review'),
        ),
        migrations.AddField(
            model_name='blogcontributor',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ticket'),
        ),
        migrations.AlterUniqueTogether(
            name='blogcontributor',
            unique_together={('contributor', 'review', 'ticket')},
        ),
    ]
