# Generated by Django 3.2 on 2022-02-15 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcontributor',
            old_name='blog',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='caption',
        ),
        migrations.AddField(
            model_name='blogcontributor',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.ticket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='contributors',
            field=models.ManyToManyField(related_name='ticket_contributions', through='blog.BlogContributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='review',
            name='contributors',
            field=models.ManyToManyField(related_name='review_contributions', through='blog.BlogContributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='blogcontributor',
            unique_together={('contributor', 'review', 'ticket')},
        ),
    ]
