# Generated by Django 3.2 on 2022-02-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollows',
            name='follows',
            field=models.ManyToManyField(to='authentication.UserFollows'),
        ),
    ]
