# Generated by Django 3.2 on 2022-02-28 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollows',
            name='follows',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
    ]
