# Generated by Django 3.2 on 2022-02-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userfollows_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollows',
            name='follows',
            field=models.ManyToManyField(related_name='_authentication_userfollows_follows_+', to='authentication.UserFollows', verbose_name='suit'),
        ),
    ]
